### ISSUE TITLE
The data file does not exist, can you share it?

### ISSUE THREAD

**Issue by rjhuang27** [lianera/SphericalHarmonicsLighting#1]
![image](https://user-images.githubusercontent.com/69796850/100577447-3e763580-331b-11eb-9085-1790f5dc5fec.png)

**Comment by lianera** [comment]
It can be found in [release](https://github.com/lianera/SphericalHarmonicsLighting/releases)  
[SphericalharmonicsLighting.zip](https://github.com/lianera/SphericalHarmonicsLighting/releases/download/v0.1.0/SphericalharmonicsLighting.zip)

**Comment by rjhuang27** [comment]
Thanks!
