### ISSUE TITLE
球坐标系是怎么定义的？

### ISSUE THREAD

**Issue by BoysFight** [lianera/SphericalHarmonicsLighting#2]
你好，代码中的球坐标定义与https://zh.wikipedia.org/wiki/%E7%90%83%E5%BA%A7%E6%A8%99%E7%B3%BB 中的不一致，貌似也和Green中论文定义方式不一致，咱们这种坐标定义方式是怎样的啊？

**Comment by lianera** [comment]
这里实际上还是用的笛卡尔坐标系，用单位向量表示方位就可以了。只不过代码里面是y朝上，文章里面是z朝上。另外其实坐标系定义关系不大，只要采样和还原一致就可以了。
