### ISSUE TITLE
光源信息

### ISSUE THREAD

**Issue by Qiuhao-Wu** [lianera/SphericalHarmonicsLighting#4]
您好，想问一下怎样从给定的一张HDRI图像中获得球形的光源信息呢

**Comment by lianera** [comment]
> 您好，想问一下怎样从给定的一张HDRI图像中获得球形的光源信息呢

首先需要确定一下这样HDRI是不是球状的，再确定映射方式，映射方式有很多种，要看这张HDRI是怎样生成的。另外HDR图像用普通的随机采样不太合适了，因为很有可能错过光源，可以逐像素采样或者对高光部分重点采样。采样后再转成球谐参数。HDR图像一般高频部分会比较多，球谐阶数需要取大一点。
