### ISSUE TITLE
两个光照投射到球面上进行可视化

### ISSUE THREAD

**Issue by Qiuhao-Wu** [lianera/SphericalHarmonicsLighting#5]
如何把cubemap显示的光照投射到球面上可视化呀

**Comment by lianera** [comment]
> 如何把cubemap显示的光照投射到球面上可视化呀

可以采样成球谐参数，用Mathematica或者Matlab在球坐标系下把对应的函数绘制出来

**Comment by Qiuhao-Wu** [comment]
> > 如何把cubemap显示的光照投射到球面上可视化呀
> 
> 可以采样成球谐参数，用Mathematica或者Matlab在球坐标系下把对应的函数绘制出来

您好，有相关教程么，我目前有了球谐系数
